const map = L.map('map').setView([48.8566, 2.3522], 3); // Centered on Europe

// Add OpenStreetMap tile layer
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
}).addTo(map);

// WWII Events
L.marker([39.9042, 116.4074]).addTo(map).bindPopup(`<strong>Japan invades China</strong><br>7/7/1937<br><p>On July 7, 1937, Japan launched a full-scale invasion of China, starting with the Marco Polo Bridge Incident, marking the beginning of the Second Sino-Japanese War.</p>`);
L.marker([48.2082, 16.3738]).addTo(map).bindPopup(`<strong>Germany annexes Austria (Anschluss)</strong><br>3/12/1938<br><p>On March 12, 1938, Germany annexed Austria into the Third Reich in a largely unopposed move, violating the Treaty of Versailles and setting the stage for further expansion.</p>`);
L.marker([50.0755, 14.4378]).addTo(map).bindPopup(`<strong>Germany occupies Czechoslovakia</strong><br>3/15/1939<br><p>On March 15, 1939, Germany invaded and occupied the remaining parts of Czechoslovakia, breaking the Munich Agreement and increasing tensions in Europe.</p>`);
L.marker([52.2297, 21.0122]).addTo(map).bindPopup(`<strong>Germany invades Poland</strong><br>9/1/1939<br><p>Germany invaded Poland on September 1, 1939, marking the official start of World War II. The UK and France declared war on Germany two days later.</p>`);
L.marker([51.9194, 19.1451]).addTo(map).bindPopup(`<strong>Soviet Union invades Eastern Poland</strong><br>9/17/1939<br><p>On September 17, 1939, the Soviet Union invaded Poland from the east, in accordance with the secret protocols of the Molotov-Ribbentrop Pact signed with Germany.</p>`);
L.marker([48.8566, 2.3522]).addTo(map).bindPopup(`<strong>Germany invades France and the Low Countries</strong><br>5/10/1940<br><p>On May 10, 1940, Germany launched a blitzkrieg against France, Belgium, the Netherlands, and Luxembourg. German forces bypassed the Maginot Line, quickly overwhelming Allied defenses.</p>`);
L.marker([47.904, 1.9093]).addTo(map).bindPopup(`<strong>France signs armistice with Germany</strong><br>6/22/1940<br><p>On June 22, 1940, following the German victory in the Battle of France, the French government signed an armistice, resulting in German occupation of the north and west of France.</p>`);
L.marker([55.7558, 37.6173]).addTo(map).bindPopup(`<strong>Germany invades the Soviet Union (Operation Barbarossa)</strong><br>6/22/1941<br><p>On June 22, 1941, Germany launched Operation Barbarossa, a massive and brutal invasion of the Soviet Union, opening the Eastern Front and breaking the non-aggression pact.</p>`);
L.marker([21.3069, -157.8583]).addTo(map).bindPopup(`<strong>Attack on Pearl Harbor</strong><br>12/7/1941<br><p>On December 7, 1941, Japan attacked the U.S. naval base at Pearl Harbor in Hawaii, drawing the United States into World War II.</p>`);
L.marker([49.3228, -0.621]).addTo(map).bindPopup(`<strong>D-Day: Allied Invasion of Normandy</strong><br>6/6/1944<br><p>On June 6, 1944, Allied forces stormed the beaches of Normandy, France, launching Operation Overlord and beginning the liberation of Western Europe from Nazi control.</p>`);
L.marker([52.52, 13.405]).addTo(map).bindPopup(`<strong>Victory in Europe Day (VE Day)</strong><br>5/8/1945<br><p>On May 8, 1945, the Allies accepted Nazi Germany’s unconditional surrender, marking the end of World War II in Europe.</p>`);
L.marker([34.3853, 132.4553]).addTo(map).bindPopup(`<strong>Atomic bombing of Hiroshima</strong><br>8/6/1945<br><p>On August 6, 1945, the United States dropped the first atomic bomb on the Japanese city of Hiroshima, causing massive destruction and loss of life.</p>`);
L.marker([32.7503, 129.8777]).addTo(map).bindPopup(`<strong>Atomic bombing of Nagasaki</strong><br>8/9/1945<br><p>On August 9, 1945, the United States dropped a second atomic bomb on Nagasaki. Combined with the devastation of Hiroshima, this led to Japan’s surrender.</p>`);
L.marker([35.6762, 139.6503]).addTo(map).bindPopup(`<strong>Japan formally surrenders (VJ Day)</strong><br>9/2/1945<br><p>On September 2, 1945, Japan officially surrendered aboard the USS Missouri, ending World War II entirely.</p>`);
L.marker([51.5074, -0.1278]).addTo(map).bindPopup(`<strong>Battle of Britain</strong><br>7/10/1940<br><p>From July to October 1940, the Royal Air Force defended the UK against massive German air assaults in the first all-air battle in history. Britain's victory ended Hitler's plans for a seaborne invasion and demonstrated that air power alone could decide a campaign.</p>`);
L.marker([59.9311, 30.3609]).addTo(map).bindPopup(`<strong>Siege of Leningrad</strong><br>9/8/1941<br><p>The Siege of Leningrad lasted nearly 900 days, resulting in the deaths of over a million civilians due to starvation, disease, and bombardment. The city's endurance became a powerful symbol of Soviet resistance.</p>`);
L.marker([48.708, 44.5133]).addTo(map).bindPopup(`<strong>Battle of Stalingrad</strong><br>7/17/1942<br><p>The Battle of Stalingrad marked the turning point in the Eastern Front. The Soviet Union decisively defeated the German Army, halting its advance into the USSR and beginning a long counter-offensive toward Berlin.</p>`);
L.marker([50.0, 6.0]).addTo(map).bindPopup(`<strong>Battle of the Bulge</strong><br>12/16/1944<br><p>The last major German offensive campaign on the Western Front, the Battle of the Bulge saw surprise attacks through the Ardennes that nearly split Allied lines. Stubborn American resistance turned the tide.</p>`);
L.marker([28.2, -177.35]).addTo(map).bindPopup(`<strong>Battle of Midway</strong><br>6/4/1942<br><p>The Battle of Midway was a crucial naval battle in the Pacific Theater. American forces, through code-breaking, ambushed and sank four Japanese aircraft carriers, halting Japan’s expansion and turning the tide of the war in the Pacific.</p>`);
L.marker([30.8333, 28.95]).addTo(map).bindPopup(`<strong>Second Battle of El Alamein</strong><br>10/23/1942<br><p>British forces under General Montgomery defeated the Afrika Korps led by Rommel. This victory in Egypt forced Axis forces to retreat across North Africa and secured the Suez Canal.</p>`);
